# Netlify Configuration without function dependencies
# Use this if the main config fails due to dependency issues

[build]
  publish = "frontend/dist"
  command = "cd frontend && npm install --force && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-simple"
  status = 200

[functions]
  directory = "netlify/functions"

