# Backup Netlify Configuration with legacy-peer-deps
# Use this if --force doesn't work

[build]
  publish = "frontend/dist"
  command = "cd frontend && npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "netlify/functions"

